name: compile

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: compile
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: zip artifacts
        run: |
          mkdir -p artifacts
          cp core/target/core-*.jar artifacts
          cp staff/target/staff-*.jar artifacts
          cp rule/target/rule-*.jar artifacts
          cp store/target/store-*.jar artifacts
          cp forecast/target/forecast-*.jar artifacts
          cp schedule/target/schedule-*.jar artifacts
          zip -r schedulesystem.zip artifacts
      - name: make a release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            schedulesystem.zip
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}