name: compile

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: compile
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: make a release draft
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            core/target/core-*.jar
            staff/target/staff-*.jar
            rule/target/rule-*.jar
            store/target/store-*.jar
            forecast/target/forecast-*.jar
            schedule/target/schedule-*.jar
          draft: true